### ISSUE TITLE
Not Identifying ERC721 contract.

### ISSUE THREAD

**Issue by shinystar1995** [nibbstack/erc721-validator#25]
I tried to detect ERC721 contract among three contracts.
0xdfc0a3a79cf50b3bbea24309ea2bc7d9e6ef24ac
0x22407b385e0f464f166f1f05abcd015278192e9e
0xd16bdccae06dfd701a59103446a17e22e9ca0ef0

Actually, the third one(0xd16...) is only ERC-721 contract.

const Web3 = require('web3');
const { ERC721Validator } = require('@nibbstack/erc721-validator');

const web3 = new Web3(new Web3.providers.HttpProvider('https://rpc.ankr.com/eth'));
const validator = new ERC721Validator(web3);

const type = await validator.basic(1, trans.contractAddress);    //1-3 contract adrs.

but, I had a result like this.
0xdfc0a3a79cf50b3bbea24309ea2bc7d9e6ef24ac
{ result: true, gas: 131451 }
0x22407b385e0f464f166f1f05abcd015278192e9e
{ result: true, gas: 131451 }
0xd16bdccae06dfd701a59103446a17e22e9ca0ef0
{ result: true, gas: 131451 }

All of them are ERC-721 contracts.

I am not sure why this happens, anybody can help me?

**Comment by AeroXi** [comment]
same problem here, did you get it to work?

**Comment by shinystar1995** [comment]
I solved it. The key it to analyze the Validator's basic function carefully. This function requires two parameters.
First one is test case index and the latter one is contract address.
so you can change test case index for validating contract address. I remember that 3 is correct for validation of ERC-721 contract.
